#### OneHot Encoder

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [98]:
df=pd.read_csv("dataset/cars.csv")

In [99]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [100]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [101]:
df["brand"].nunique() ## no. of unique brands

32

In [102]:
df["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [103]:
df["owner"].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

#### 1. OneHotEncoding using Pandas

In [104]:
pd.get_dummies(df,columns=["fuel","owner"],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

#### 2. K-1 OneHotEncoding

In [105]:
pd.get_dummies(df,columns=["fuel","owner"],drop_first=True,dtype=int)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

we don't use pandas while using OneHotEncoding as padas don't store how the columns are placed ,result can be changed at retry. So we using scikit-learn class

#### 3. OneHotEncoding using Scikit-learn

In [106]:
from sklearn.model_selection import train_test_split

In [107]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,:-1],test_size=0.2,random_state=44)

In [108]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)
X_train_new=ohe.fit_transform(X_train[["fuel","owner"]])

In [109]:
X_test_new=ohe.transform(X_test[["fuel","owner"]])

In [110]:
X_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [111]:
type(X_test_new)

numpy.ndarray

In [112]:
np.hstack((X_train[["brand","km_driven"]].values, X_train_new)).shape

(6502, 9)

In [113]:

combined = np.hstack((X_train[["brand","km_driven"]].values, X_train_new))

df1 = pd.DataFrame(combined)
df1.head()

          0      1  2  3  4  5  6  7  8
0      Tata  53000  0  0  1  0  0  0  0
1  Mahindra  80000  1  0  0  0  0  0  0
2    Maruti  90000  1  0  0  0  0  0  0
3    Maruti  99361  0  0  1  0  1  0  0
4    Maruti  41779  0  0  1  0  0  0  0

#### 4. OneHotEncoding with Top Categories

In [114]:
counts=df['brand'].value_counts()

In [115]:
# we have to apply onehot encoder on fuel and owner than rejoin it with dataset and for branch encoding we take only cars count>=100

In [116]:
df["brand"].nunique()
threshold=100

In [121]:
repl=counts[counts<=threshold].index 
repl 
#categories that has cars less than 100

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Kia',
       'Ambassador', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='str', name='brand')

In [120]:
pd.get_dummies(df["brand"].replace(repl,'uncommon'),dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
859,0,0,0,0,0,0,1,0,0,0,0,0,0
2705,0,0,0,0,0,0,0,0,0,0,0,0,1
908,0,0,0,0,1,0,0,0,0,0,0,0,0
6318,0,0,0,0,0,0,0,0,0,1,0,0,0
4607,0,0,1,0,0,0,0,0,0,0,0,0,0