## Fetching from API

In [1]:
import pandas as pd
import requests

In [3]:
req = requests.get("https://api.exchangerate-api.com/v4/latest/INR")
req

In [4]:
req.json()

{'provider': 'https://www.exchangerate-api.com',
 'WARNING_UPGRADE_TO_V6': 'https://www.exchangerate-api.com/docs/free',
 'terms': 'https://www.exchangerate-api.com/terms',
 'base': 'INR',
 'date': '2026-03-21',
 'time_last_updated': 1774051201,
 'rates': {'INR': 1,
  'AED': 0.0392,
  'AFN': 0.688,
  'ALL': 0.898,
  'AMD': 4.04,
  'ANG': 0.0191,
  'AOA': 10.13,
  'ARS': 15.5,
  'AUD': 0.0151,
  'AWG': 0.0191,
  'AZN': 0.0182,
  'BAM': 0.0181,
  'BBD': 0.0214,
  'BDT': 1.32,
  'BGN': 0.0181,
  'BHD': 0.00401,
  'BIF': 32.2,
  'BMD': 0.0107,
  'BND': 0.0137,
  'BOB': 0.0746,
  'BRL': 0.0562,
  'BSD': 0.0107,
  'BTN': 1,
  'BWP': 0.151,
  'BYN': 0.0324,
  'BZD': 0.0214,
  'CAD': 0.0147,
  'CDF': 24.94,
  'CHF': 0.00843,
  'CLF': 0.000247,
  'CLP': 9.76,
  'CNH': 0.0738,
  'CNY': 0.0742,
  'COP': 39.79,
  'CRC': 5.04,
  'CUP': 0.256,
  'CVE': 1.02,
  'CZK': 0.227,
  'DJF': 1.9,
  'DKK': 0.0692,
  'DOP': 0.651,
  'DZD': 1.42,
  'EGP': 0.56,
  'ERN': 0.16,
  'ETB': 1.7,
  'EUR': 0.00926,
  'FJD': 0.0237,
  'FKP': 0.00802,
  'FOK': 0.0692,
  'GBP': 0.00801,
  'GEL': 0.0291,
  'GGP': 0.00802,
  'GHS': 0.117,
  'GIP': 0.00802,
  'GMD': 0.792,
  'GNF': 93.62,
  'GTQ': 0.0824,
  'GYD': 2.26,
  'HKD': 0.0838,
  'HNL': 0.285,
  'HRK': 0.0699,
  'HTG': 1.42,
  'HUF': 3.63,
  'IDR': 181.19,
  'ILS': 0.0333,
  'IMP': 0.00802,
  'IQD': 14.18,
  'IRR': 12458.6,
  'ISK': 1.33,
  'JEP': 0.00802,
  'JMD': 1.69,
  'JOD': 0.00757,
  'JPY': 1.7,
  'KES': 1.4,
  'KGS': 0.935,
  'KHR': 43.64,
  'KID': 0.0151,
  'KMF': 4.56,
  'KRW': 16.01,
  'KWD': 0.00328,
  'KYD': 0.0089,
  'KZT': 5.15,
  'LAK': 233.67,
  'LBP': 955.52,
  'LKR': 3.34,
  'LRD': 1.97,
  'LSL': 0.181,
  'LYD': 0.0691,
  'MAD': 0.1,
  'MDL': 0.187,
  'MGA': 44.82,
  'MKD': 0.573,
  'MMK': 22.58,
  'MNT': 38.59,
  'MOP': 0.0863,
  'MRU': 0.433,
  'MUR': 0.508,
  'MVR': 0.166,
  'MWK': 18.68,
  'MXN': 0.191,
  'MYR': 0.0423,
  'MZN': 0.683,
  'NAD': 0.181,
  'NGN': 14.42,
  'NIO': 0.396,
  'NOK': 0.102,
  'NPR': 1.6,
  'NZD': 0.0183,
  'OMR': 0.0041,
  'PAB': 0.0107,
  'PEN': 0.037,
  'PGK': 0.0465,
  'PHP': 0.64,
  'PKR': 3,
  'PLN': 0.0396,
  'PYG': 70.01,
  'QAR': 0.0389,
  'RON': 0.0471,
  'RSD': 1.09,
  'RUB': 0.892,
  'RWF': 15.56,
  'SAR': 0.04,
  'SBD': 0.0853,
  'SCR': 0.158,
  'SDG': 4.84,
  'SEK': 0.0998,
  'SGD': 0.0137,
  'SHP': 0.00802,
  'SLE': 0.263,
  'SLL': 262.6,
  'SOS': 6.19,
  'SRD': 0.408,
  'SSP': 48.96,
  'STN': 0.227,
  'SYP': 1.21,
  'SZL': 0.181,
  'THB': 0.351,
  'TJS': 0.102,
  'TMT': 0.0373,
  'TND': 0.031,
  'TOP': 0.0254,
  'TRY': 0.473,
  'TTD': 0.0728,
  'TVD': 0.0151,
  'TWD': 0.341,
  'TZS': 27.8,
  'UAH': 0.469,
  'UGX': 40.4,
  'USD': 0.0107,
  'UYU': 0.437,
  'UZS': 130.42,
  'VES': 4.88,
  'VND': 281.87,
  'VUV': 1.28,
  'WST': 0.029,
  'XAF': 6.08,
  'XCD': 0.0288,
  'XCG': 0.0191,
  'XDR': 0.00781,
  'XOF': 6.08,
  'XPF': 1.11,
  'YER': 2.56,
  'ZAR': 0.181,
  'ZMW': 0.209,
  'ZWG': 0.27,
  'ZWL': 0.27}}

#### To convert json into dataframe

In [5]:
pd.DataFrame(req.json()).head()

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-21,1774051201,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-21,1774051201,0.0392
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-21,1774051201,0.6880
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-21,1774051201,0.8980
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-21,1774051201,4.0400

In [6]:
df=pd.DataFrame()

In [7]:
df

Empty DataFrame
Columns: []
Index: []

In [8]:
for i in range(5):
    req = requests.get("https://api.exchangerate-api.com/v4/latest/INR")
    df=df.append(pd.DataFrame(req.json()),ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [9]:
df.shape

(0, 0)